version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      TZ: UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
