server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchwait: 5s       # Wait up to 5s to batch before sending
    batchsize: 102400   # Maximum batch size of 100KB before sending


scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{6}Z)(.*)$'
          output:
            timestamp: "${timestamp}"
      - timestamp:
          source: timestamp
          format: RFC3339Nano
          